FROM alpine:latest
RUN groupadd -r myuser && useradd -r -g myuser myuser
# Etiqueta del maintainer
LABEL maintainer="nuamx.com"
ARG jar_file_path
# Copia el archivo JAR o binario compilado a la raíz de la imagen
COPY $jar_file_path app.jar
USER myuser
# Comando de entrada para ejecutar la aplicación (ajusta según tu aplicación)
CMD ["java", "-jar", "/app.jar"]