FROM eclipse-temurin:17
# Etiqueta del maintainer
LABEL maintainer="nuamx.com"
# Copia el archivo JAR o binario compilado a la raíz de la imagen
COPY target/*.jar app.jar
# Comando de entrada para ejecutar la aplicación (ajusta según tu aplicación)
CMD ["java", "-jar", "/app.jar"]